name: geogcn
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - numpy=1.18.1
  - pandas=1.0.1
  - pillow=7.0.0
  - matplotlib=3.1.3
  - scipy=1.4.1
  - scikit-learn=0.22.2
  - scikit-image=0.16.2
  - cython
  - jupyter
  - ipython
  - ipykernel
  - ipywidgets
  - nbconvert
  - nbformat
  - jupyterlab
  - notebook
  - boost
  - cudatoolkit=10.1
  - pip
  - pip:
      - https://download.pytorch.org/whl/cu101/torch-1.4.0-cp37-cp37m-win_amd64.whl
      - https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp37-cp37m-win_amd64.whl
      - https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_cluster-1.5.2-cp37-cp37m-win_amd64.whl
      - https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_scatter-2.0.4-cp37-cp37m-win_amd64.whl
      - https://data.pyg.org/whl/torch-1.4.0%2Bcu101/torch_sparse-0.6.0-cp37-cp37m-win_amd64.whl
      - torch-geometric==1.4.2
      - chardet==3.0.4
      - cycler==0.10.0
      - googledrivedownloader==0.4
      - h5py==2.10.0
      - idna==2.9
      - imageio==2.8.0
      - isodate==0.6.0
      - joblib==0.14.1
      - kiwisolver==1.1.0
      - llvmlite==0.31.0
      - numba==0.48.0
      - plyfile==0.7.1
      - pyparsing==2.4.6
      - pyqt5-sip==4.19.18
      - pyqtwebengine==5.12.1
      - pywavelets==1.1.1
      - rdflib==4.2.2
      - requests==2.23.0
      - urllib3==1.25.8
